import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { site, games, guides, news, videos, codes, releases, gameBySlug } from '../src/data.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const base = (process.env.SITE_BASE || '').replace(/\/$/, '');
const siteUrl = (process.env.SITE_URL || 'http://localhost:4174').replace(/\/$/, '');
const buildDate = '2026-09-09';

const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const href = route => route.startsWith('http') ? route : `${base}${route.startsWith('/') ? route : `/${route}`}`;
const absolute = route => `${siteUrl}${route.startsWith('/') ? route : `/${route}`}`;
const asset = name => href(`/assets/${name}`);
const routeFile = route => route === '/' ? path.join(out, 'index.html') : path.join(out, route.replace(/^\//,'').replace(/\/$/,''), 'index.html');
const game = slug => gameBySlug(slug) || games[0];

const icon = (item, cls='') => `<img class="${cls}" src="${asset(item.image)}" alt="${esc(item.name)} app icon" width="64" height="64" loading="lazy">`;
const badge = (text, tone='teal') => `<span class="badge badge-${tone}">${esc(text)}</span>`;
const gameCard = item => `<a class="game-card" href="${href(`/games/${item.slug}/`)}">${icon(item)}<span><strong>${esc(item.name)}</strong><small>${esc(item.genre)}</small><em>${esc(item.status)} · ${esc(item.rank)}</em></span></a>`;
const storyCard = (item, section='guides') => {
  const g = game(item.game);
  return `<article class="story-card"><a class="story-image" href="${href(`/${section}/${item.slug}/`)}"><img src="${asset(g.hero)}" alt="${esc(g.name)} gameplay artwork" width="640" height="360" loading="lazy"></a><div>${badge(item.type, section === 'news' ? 'orange' : 'teal')}<h3><a href="${href(`/${section}/${item.slug}/`)}">${esc(item.title)}</a></h3><p>${esc(item.dek)}</p><small>${section === 'guides' ? `${esc(item.time)} read · ${esc(item.updated)}` : esc(item.date)}</small></div></article>`;
};
const breadcrumbs = items => `<nav class="breadcrumbs" aria-label="Breadcrumb">${items.map((item, i) => i === items.length - 1 ? `<span aria-current="page">${esc(item.label)}</span>` : `<a href="${href(item.url)}">${esc(item.label)}</a>`).join('<span aria-hidden="true">/</span>')}</nav>`;

function header(active='') {
  const nav = [['Games','/games/'],['Rankings','/rankings/'],['New releases','/new-games/'],['Guides','/guides/'],['News','/news/'],['Videos','/videos/'],['Codes','/codes/']];
  return `<header class="site-header">
    <div class="trend-bar"><div class="shell trend-inner"><div class="trend-links"><b>Trending</b><a href="${href('/guides/whiteout-survival-upgrade-priority/')}">Whiteout Survival upgrades</a><a href="${href('/news/monopoly-go-event-calendar/')}">MONOPOLY GO! events</a><a href="${href('/guides/roblox-best-adventures/')}">Best Roblox games</a></div><span class="data-note"><i></i>Editorial demo · US</span></div></div>
    <div class="shell masthead"><a class="brand" href="${href('/')}"><span class="brand-mark">P</span><span>PLAY<strong>SCOUT</strong></span></a>
      <button class="menu-button" type="button" aria-expanded="false" aria-controls="primary-nav"><span></span><span></span><span></span><span class="sr-only">Open navigation</span></button>
      <nav id="primary-nav" aria-label="Primary navigation">${nav.map(([label,url]) => `<a ${active === label ? 'aria-current="page" class="active"' : ''} href="${href(url)}">${label}</a>`).join('')}</nav>
      <a class="search-trigger" href="${href('/search/')}"><span aria-hidden="true">⌕</span><span>Search</span><kbd>/</kbd></a>
    </div>
  </header>`;
}

function footer() {
  return `<footer><div class="shell footer-grid"><div><a class="brand brand-footer" href="${href('/')}"><span class="brand-mark">P</span><span>PLAY<strong>SCOUT</strong></span></a><p>Useful mobile-game answers, clear sourcing and paths that help players decide what to do next.</p></div><div><strong>Explore</strong><a href="${href('/games/')}">Games</a><a href="${href('/rankings/')}">Rankings</a><a href="${href('/guides/')}">Guides</a><a href="${href('/videos/')}">Videos</a></div><div><strong>About</strong><a href="${href('/about/sources/')}">Sources & methodology</a><a href="${href('/about/editorial-policy/')}">Editorial policy</a><a href="${href('/sitemap.xml')}">Sitemap</a></div><div class="demo-note"><strong>Preview status</strong><p>Rankings, dates and redeem codes are sample editorial data for product validation. Verify them before production use.</p></div></div><div class="shell footer-bottom"><span>© 2026 PlayScout</span><span>Built for fast, accessible discovery</span></div></footer>`;
}

function layout({ title, description, route='/', active='', body, type='website', jsonLd=[] , noindex=false }) {
  const canonical = absolute(route);
  const schemas = [
    { '@context':'https://schema.org', '@type':'Organization', name:site.name, url:absolute('/'), logo:absolute('/assets/whiteout.jpg') },
    { '@context':'https://schema.org', '@type':'WebSite', name:site.name, url:absolute('/'), potentialAction:{ '@type':'SearchAction', target:`${absolute('/search/')}?q={search_term_string}`, 'query-input':'required name=search_term_string' } },
    ...jsonLd,
  ];
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ${site.name}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}">${noindex ? '<meta name="robots" content="noindex,follow">' : '<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1">'}<meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="${site.name}"><meta property="og:image" content="${absolute('/assets/whiteout-shot.jpg')}"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#12283d"><link rel="icon" href="${asset('whiteout.jpg')}"><link rel="stylesheet" href="${href('/styles.css')}"><script type="application/ld+json">${JSON.stringify(schemas)}</script></head><body>${header(active)}<main>${body}</main>${footer()}<script src="${href('/app.js')}" defer></script></body></html>`;
}

const sectionHead = (kicker,title,linkLabel='',linkRoute='') => `<div class="section-heading"><div><span class="kicker">${esc(kicker)}</span><h2>${esc(title)}</h2></div>${linkLabel ? `<a href="${href(linkRoute)}">${esc(linkLabel)} <span aria-hidden="true">→</span></a>` : ''}</div>`;
const pageHero = (kicker,title,text,stats=[]) => `<section class="page-hero"><div class="shell"><span class="kicker">${esc(kicker)}</span><h1>${esc(title)}</h1><p>${esc(text)}</p>${stats.length ? `<div class="page-stats">${stats.map(([n,l]) => `<span><b>${esc(n)}</b><span>${esc(l)}</span></span>`).join('')}</div>` : ''}</div></section>`;
const sourceBox = () => `<aside class="source-box"><span class="kicker">TRANSPARENCY</span><h3>How to read this preview</h3><p>Visible rankings and freshness labels demonstrate the publishing model. A production editor must verify every changing fact against its linked source.</p><a href="${href('/about/sources/')}">Read our source policy →</a></aside>`;

function homePage() {
  const lead = guides[0]; const leadGame = game(lead.game);
  const chartGames = [games[4],games[6],games[7],games[10],games[9]];
  const body = `<section class="shell hero-grid">
    <a class="lead-story" href="${href(`/guides/${lead.slug}/`)}"><img src="${asset(leadGame.hero)}" alt="${esc(leadGame.name)} gameplay scene" width="900" height="620"><span class="scrim"></span><div><span class="eyebrow">EDITOR'S GUIDE · ${lead.time.toUpperCase()}</span><h1>${esc(lead.title)}</h1><p>${esc(lead.dek)}</p><small>Player-tested route · ${esc(lead.updated)}</small></div></a>
    <section class="updates-panel">${sectionHead('TODAY','Latest updates','All','/news/')}<div class="updates-list">${news.slice(0,6).map((n,i)=>`<a href="${href(`/news/${n.slug}/`)}"><time>${['14:20','13:42','12:18','10:55','09:30','08:15'][i]}</time><span><b>${esc(n.type)}</b>${esc(n.title)}</span></a>`).join('')}</div></section>
    <section class="chart-panel">${sectionHead('LIVE DATA','Mobile charts','View all','/rankings/')}<div class="segmented" role="tablist" aria-label="Chart type"><button class="selected" data-chart="paid" type="button">Paid</button><button data-chart="free" type="button">Free</button><button data-chart="grossing" type="button">Grossing</button></div><div class="mini-ranking" data-ranking-list>${chartGames.map((g,i)=>`<a href="${href(`/games/${g.slug}/`)}"><b>${i+1}</b>${icon(g)}<span><strong>${esc(g.name)}</strong><small>${esc(g.genre)}</small></span><em>${i===1?'▲ 1':'—'}</em></a>`).join('')}</div><small class="sample-label">Sample chart snapshot · methodology available</small></section>
  </section>
  <section class="shell">${sectionHead('DISCOVER','Popular games right now','Explore all games','/games/')}<div class="game-rail">${games.slice(0,8).map(gameCard).join('')}</div></section>
  <section class="shell">${sectionHead('PLAY NEXT','New and upcoming','Full release calendar','/new-games/')}<div class="release-grid">${releases.slice(0,4).map(r=>{const g=game(r.game);return `<a href="${href(`/games/${g.slug}/`)}"><time>${esc(r.date)}</time>${icon(g)}<span><strong>${esc(g.name)}</strong><small>${esc(r.note)}</small><em>${esc(r.label)}</em></span></a>`}).join('')}</div></section>
  <section class="shell">${sectionHead('PLAYER-TESTED','Updated guides','Browse all guides','/guides/')}<div class="story-grid">${guides.slice(0,6).map(g=>storyCard(g)).join('')}</div></section>
  <section class="video-band"><div class="shell">${sectionHead('WATCH & LEARN','Video tutorials and player perspectives','All videos','/videos/')}<div class="video-grid">${videos.slice(0,3).map(videoCard).join('')}</div></div></section>
  <section class="shell split-section"><div>${sectionHead('THE LATEST','News that changes how you play','News channel','/news/')}<div class="compact-feed">${news.slice(0,6).map(n=>compactStory(n,'news')).join('')}</div></div><div>${sectionHead('REWARDS','Codes to verify','All codes','/codes/')}<div class="code-stack">${codes.slice(0,5).map(codeRow).join('')}</div></div></section>
  <section class="shell community"><div><span class="kicker">PLAYER KNOWLEDGE</span><h2>Useful tips, with context</h2><p>Player ideas are labelled, connected to a game version and reviewed before they become evergreen guides.</p><a class="button" href="${href('/about/editorial-policy/')}">How contributions work</a></div><div>${guides.slice(6,10).map(g=>`<a href="${href(`/guides/${g.slug}/`)}"><span class="avatar">${esc(game(g.game).name.slice(0,2).toUpperCase())}</span><span><small>PLAYER TIP · ${esc(game(g.game).name)}</small><strong>${esc(g.title)}</strong><em>${esc(g.answer)}</em></span></a>`).join('')}</div></section>`;
  return layout({title:site.tagline,description:site.description,body,active:'',route:'/'});
}

function videoCard(v) { const g=game(v.game); return `<article class="video-card"><a class="video-thumb" href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener noreferrer"><img src="https://i.ytimg.com/vi/${v.id}/hqdefault.jpg" alt="Video thumbnail for ${esc(v.title)}" width="480" height="270" loading="lazy"><span class="play" aria-hidden="true">▶</span><time>${esc(v.duration)}</time></a><div>${badge('External video','lime')}<h3><a href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener noreferrer">${esc(v.title)} ↗</a></h3><p>${esc(v.summary)}</p><small>${esc(g.name)} · ${esc(v.channel)}</small></div></article>`; }
function compactStory(item,section) { const g=game(item.game); return `<a class="compact-story" href="${href(`/${section}/${item.slug}/`)}">${icon(g)}<span><small>${esc(item.type)} · ${esc(g.name)}</small><strong>${esc(item.title)}</strong><em>${esc(item.date || item.updated)}</em></span></a>`; }
function codeRow(c) { const g=game(c.game); return `<div class="code-row">${icon(g)}<span><strong>${esc(g.name)}</strong><code>${esc(c.code)}</code><small>${esc(c.status)}</small></span><button type="button" data-copy="${esc(c.code)}">Copy</button></div>`; }

function gamesPage() {
  const body = `${pageHero('GAME FINDER','Find your next game','Browse a focused starter catalog by platform, genre and current editorial signal.',[['12','game hubs'],['7','genres'],['2','mobile platforms']])}<section class="shell"><div class="filter-bar" data-filter-group="games"><label>Filter games <input type="search" placeholder="Search by name or genre" data-game-search></label><button class="selected" data-filter="all">All</button><button data-filter="strategy">Strategy</button><button data-filter="puzzle">Puzzle</button><button data-filter="adventure">Adventure</button><button data-filter="paid">Paid chart</button></div><p class="result-count" aria-live="polite" data-result-count>${games.length} games shown</p><div class="catalog-grid">${games.map(g=>`<div data-game-item data-search="${esc(`${g.name} ${g.genre} ${g.platforms} ${g.rank}`.toLowerCase())}">${gameCard(g)}</div>`).join('')}</div>${sectionHead('BROWSE BY NEED','Start with a useful collection')}<div class="collection-grid"><a href="${href('/rankings/')}"><b>01</b><strong>Chart leaders</strong><span>See rank, movement and methodology</span></a><a href="${href('/new-games/')}"><b>02</b><strong>New releases</strong><span>Plan what to play next</span></a><a href="${href('/guides/')}"><b>03</b><strong>Beginner friendly</strong><span>Games with clear starting routes</span></a><a href="${href('/videos/')}"><b>04</b><strong>Watch first</strong><span>Learn through external creators</span></a></div></section>`;
  return layout({title:'Browse mobile games',description:'Find mobile games by platform, genre, price and editorial heat, with direct paths to guides, videos, codes and updates.',route:'/games/',active:'Games',body});
}

function gamePage(g) {
  const relatedGuides = guides.filter(x=>x.game===g.slug); const relatedCodes=codes.filter(x=>x.game===g.slug); const v=videos.find(x=>x.game===g.slug)||videos[0];
  const trail=[{label:'Home',url:'/'},{label:'Games',url:'/games/'},{label:g.name}];
  const body = `<section class="game-hero"><div class="shell">${breadcrumbs(trail)}<div class="game-heading">${icon(g,'game-icon')}<div><span class="kicker">GAME HUB</span><h1>${esc(g.name)}</h1><p>${esc(g.summary)}</p><div class="game-meta"><span>${esc(g.genre)}</span><span>${esc(g.platforms)}</span><span>${esc(g.developer)}</span></div></div><a class="button button-lime" href="${esc(g.store)}" target="_blank" rel="noopener noreferrer">View store ↗</a></div></div></section><nav class="subnav" aria-label="Game sections"><div class="shell"><a href="#start">Start here</a><a href="#guides">Guides</a><a href="#video">Videos</a><a href="#codes">Codes</a><a href="#sources">Sources</a></div></nav>
  <div class="shell game-layout"><article><section id="start" class="start-card"><span class="kicker">START HERE</span><h2>Your first three moves</h2><p>A simple path from opening the game to making informed progress.</p><ol><li><b>1</b><strong>Learn the main loop</strong><span>Play one short session before spending scarce currency.</span></li><li><b>2</b><strong>Protect rare resources</strong><span>Keep speedups, premium currency and one-time items until goals are clear.</span></li><li><b>3</b><strong>Use a focused guide</strong><span>Pick the guide matching your immediate blocker.</span></li></ol></section>
  <section id="guides">${sectionHead('PRACTICAL HELP',`${g.name} guides`)}<div class="hub-guide-grid">${(relatedGuides.length?relatedGuides:guides.slice(0,4)).map(x=>`<a href="${href(`/guides/${x.slug}/`)}">${badge(x.type)}<h3>${esc(x.title)}</h3><p>${esc(x.dek)}</p><small>${esc(x.time)} · ${esc(x.updated)}</small></a>`).join('')}</div></section>
  <section id="video">${sectionHead('WATCH','Video walkthrough')}<div class="featured-video"><iframe src="https://www.youtube-nocookie.com/embed/${v.id}" title="${esc(v.title)}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><div><span class="kicker">EXTERNAL VIDEO</span><h3>${esc(v.title)}</h3><p>${esc(v.summary)}</p><a href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener noreferrer">Watch on YouTube ↗</a></div></div></section>
  </article><aside class="game-sidebar"><section class="fact-card"><span class="kicker">AT A GLANCE</span><h2>${esc(g.name)}</h2><dl><div><dt>Developer</dt><dd>${esc(g.developer)}</dd></div><div><dt>Platforms</dt><dd>${esc(g.platforms)}</dd></div><div><dt>Genre</dt><dd>${esc(g.genre)}</dd></div><div><dt>Demo heat</dt><dd>${g.score}/100</dd></div></dl></section><section id="codes" class="fact-card"><span class="kicker">REDEEM CODES</span><h2>Code check</h2>${relatedCodes.length?relatedCodes.map(codeRow).join(''):'<p>No game-specific code is listed in this preview. Check the codes hub for verified updates.</p>'}<a href="${href('/codes/')}">Open codes hub →</a></section><section id="sources">${sourceBox()}</section></aside></div><section class="shell related-section">${sectionHead('KEEP EXPLORING','Related game hubs','All games','/games/')}<div class="game-rail">${games.filter(x=>x.slug!==g.slug).slice(0,5).map(gameCard).join('')}</div></section>`;
  const jsonLd=[{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:trail.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.label,item:absolute(x.url||`/games/${g.slug}/`)}))},{'@context':'https://schema.org','@type':'VideoObject',name:v.title,description:v.summary,thumbnailUrl:`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`,uploadDate:'2025-01-01',embedUrl:`https://www.youtube-nocookie.com/embed/${v.id}`}];
  return layout({title:`${g.name} guides, videos and tips`,description:g.summary,route:`/games/${g.slug}/`,active:'Games',body,jsonLd});
}

function channelPage(kind) {
  const isGuide=kind==='guides'; const list=isGuide?guides:news; const title=isGuide?'Mobile game guides':'Mobile game news'; const active=isGuide?'Guides':'News';
  const body=`${pageHero(isGuide?'PLAYER-TESTED KNOWLEDGE':'UPDATES WITH CONTEXT',title,isGuide?'Step-by-step help, beginner routes and strategy explainers connected to complete game hubs.':'Patch notes, events and chart movement explained through the decisions they create for players.',[[String(list.length),'featured stories'],['12','game hubs'],['100%','crawlable links']])}<div class="shell channel-layout"><section><div class="filter-bar"><a class="selected" href="${href(`/${kind}/`)}">All</a><a href="${href(`/${kind}/?topic=beginners`)}">Beginners</a><a href="${href(`/${kind}/?topic=strategy`)}">Strategy</a><a href="${href(`/${kind}/?topic=events`)}">Events</a></div><div class="story-grid story-grid-channel">${list.map(x=>storyCard(x,kind)).join('')}</div></section><aside><section class="side-list"><span class="kicker">POPULAR GAMES</span><h2>Keep exploring</h2>${games.slice(0,6).map(gameCard).join('')}</section>${sourceBox()}</aside></div>`;
  return layout({title,description:isGuide?'Practical mobile game guides and strategies with update labels, quick answers and related video tutorials.':'Mobile game updates, events, releases and chart stories connected to useful guides and game hubs.',route:`/${kind}/`,active,body});
}

function articlePage(item,kind) {
  const g=game(item.game); const isGuide=kind==='guides'; const title=item.title; const trail=[{label:'Home',url:'/'},{label:isGuide?'Guides':'News',url:`/${kind}/`},{label:title}];
  const sections=isGuide?item.sections:['What changed','What it means for players','What to check next']; const quick=isGuide?item.answer:`${item.dek} This preview shows how a verified update would connect to the affected game hub and follow-up guide.`;
  const body=`<div class="shell article-wrap"><header class="article-head">${breadcrumbs(trail)}${badge(item.type,isGuide?'teal':'orange')}<h1>${esc(title)}</h1><p class="dek">${esc(item.dek)}</p><div class="byline"><span>By ${site.author}</span><span>${esc(item.updated||item.date)}</span><span>Editorial demo</span></div></header><article class="article-body"><div class="answer-box"><strong>${isGuide?'Quick answer':'Player impact'}</strong><p>${esc(quick)}</p></div><img src="${asset(g.hero)}" alt="${esc(g.name)} gameplay artwork" width="900" height="500"><p>${esc(g.summary)} This page is built as a reusable editorial template: the answer appears first, the supporting steps follow, and the update record and sources remain visible.</p>${sections.map((s,i)=>`<section id="section-${i+1}"><h2>${esc(s)}</h2><p>${esc(articleParagraph(g,item,i,isGuide))}</p>${isGuide&&i===1?`<div class="tip-box"><strong>Player tip</strong><p>Test one change at a time, record the result, and keep enough resources to reverse course after an update.</p></div>`:''}</section>`).join('')}<section><h2>Next steps</h2><p>Continue with the complete ${esc(g.name)} hub, compare the related guides below, or open the source policy to see how changing facts should be checked.</p><div class="article-actions"><a class="button" href="${href(`/games/${g.slug}/`)}">Open ${esc(g.name)} hub</a><a class="button button-secondary" href="${href(isGuide?'/videos/':'/guides/')}">${isGuide?'Watch tutorials':'Find a guide'}</a></div></section></article><aside class="article-sidebar"><nav class="toc" aria-label="On this page"><strong>On this page</strong>${sections.map((s,i)=>`<a href="#section-${i+1}">${esc(s)}</a>`).join('')}<a href="${href(`/games/${g.slug}/`)}">${esc(g.name)} hub</a></nav>${sourceBox()}<section class="side-list"><span class="kicker">RELATED</span><h2>Continue reading</h2>${(isGuide?guides:news).filter(x=>x.slug!==item.slug).slice(0,4).map(x=>`<a href="${href(`/${kind}/${x.slug}/`)}">${esc(x.title)}</a>`).join('')}</section></aside></div>`;
  const jsonLd=[{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:trail.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.label,item:absolute(x.url||`/${kind}/${item.slug}/`)}))},{'@context':'https://schema.org','@type':isGuide?'Article':'NewsArticle',headline:title,description:item.dek,datePublished:'2026-09-05',dateModified:buildDate,author:{'@type':'Organization',name:site.author},mainEntityOfPage:absolute(`/${kind}/${item.slug}/`),image:absolute(`/assets/${g.hero}`)}];
  return layout({title,description:item.dek,route:`/${kind}/${item.slug}/`,active:isGuide?'Guides':'News',type:'article',body,jsonLd});
}

function articleParagraph(g,item,i,isGuide){
  const guide=[`Start from the immediate decision in ${g.name}: what must be completed now, what can wait, and which resource is hardest to replace. The safest route preserves options while still moving the main progression system forward.`,`Use the visible objective as a checkpoint. Compare the cost of the next action with the event or level reward, then choose the smallest step that proves the strategy works. Avoid spending every saved item on a single attempt.`,`After a patch or live event begins, verify the game version and repeat a short test. If the result differs, mark the tactic for review before sharing it as a fixed rule.`];
  const update=[`The update matters because it changes a visible system around ${g.name}. Players should confirm the in-game notice and official channel before changing a saved plan.`,`For most players, the useful question is whether to act now, save resources or wait for more information. We connect this update to the relevant hub so the answer remains easy to find after the headline ages.`,`Check the related guide, current in-game event screen and linked official source. Any material correction should update the page date and change log.`];
  return (isGuide?guide:update)[i];
}

function rankingsPage(){
  const rankSets=[['Paid',games.slice(4,11)],['Free',[games[3],games[2],games[0],games[8],games[11],games[1]]],['Grossing',[games[1],games[5],games[0],games[2],games[11],games[3]]]];
  const body=`${pageHero('STORE CHARTS + EDITORIAL CONTEXT','Mobile game rankings','Compare sample free, paid and grossing charts, then open each game hub for guides and context.',[['3','chart views'],['12','linked game hubs'],['Daily','planned refresh']])}<section class="shell"><div class="filter-bar ranking-controls" role="tablist" aria-label="Ranking type">${rankSets.map(([name],i)=>`<button type="button" data-rank-tab="${name.toLowerCase()}" class="${i===0?'selected':''}">${name}</button>`).join('')}<a class="push" href="${href('/about/sources/')}">Methodology →</a></div>${rankSets.map(([name,set],si)=>`<section class="rank-section ${si?'is-hidden':''}" data-rank-panel="${name.toLowerCase()}">${sectionHead('UNITED STATES · IPHONE',`Top ${name.toLowerCase()} games`)}<div class="rank-table"><div class="rank-head"><span>Rank</span><span>Game</span><span>Genre</span><span>Move</span><span>Heat</span><span>Status</span></div>${set.map((g,i)=>`<a class="rank-row" href="${href(`/games/${g.slug}/`)}"><b>${i+1}</b><span class="rank-game">${icon(g)}<span><strong>${esc(g.name)}</strong><small>${esc(g.developer)}</small></span></span><span>${esc(g.genre.split(' · ')[0])}</span><span class="${i%3===1?'up':''}">${i%3===1?'▲ 1':'—'}</span><span>${g.score}/100</span><small>${esc(g.status)}</small></a>`).join('')}</div></section>`).join('')}<div class="method-grid">${sourceBox()}<article><span class="kicker">THREE DIFFERENT SIGNALS</span><h2>Rank is not the same as popularity</h2><p><b>Store rank</b> records a platform chart position. <b>Heat score</b> is a transparent editorial composite for discovery. <b>Editor picks</b> are qualitative recommendations. Production data keeps these fields separate.</p></article></div></section>`;
  return layout({title:'Mobile game rankings',description:'Browse mobile game ranking tables with linked game hubs, chart context and transparent methodology.',route:'/rankings/',active:'Rankings',body});
}

function releasesPage(){
  const body=`${pageHero('RELEASE CALENDAR','New and upcoming mobile games','A scannable calendar for launches, content drops and live events, each linked to a game hub.',[['8','tracked dates'],['2','platforms'],['Weekly','editor review']])}<section class="shell"><div class="filter-bar"><button class="selected">All dates</button><button>This week</button><button>Upcoming</button><button>iOS</button><button>Android</button></div><div class="release-list">${releases.map(r=>{const g=game(r.game);return `<a href="${href(`/games/${g.slug}/`)}"><time>${esc(r.date)}</time>${icon(g)}<span><strong>${esc(g.name)}</strong><small>${esc(g.summary)}</small></span><em>${esc(r.label)}</em><b>${esc(r.note)}</b></a>`}).join('')}</div>${sectionHead('READY NOW','Established games to explore','Browse all','/games/')}<div class="game-rail">${games.slice(0,6).map(gameCard).join('')}</div></section>`;
  return layout({title:'New and upcoming mobile games',description:'Discover new mobile game launches, upcoming events and content updates with direct links to game hubs.',route:'/new-games/',active:'New releases',body});
}

function videosPage(){
  const featured=videos[0], g=game(featured.game);
  const body=`${pageHero('WATCH & LEARN','Mobile game video guides','Specific tutorials and player perspectives with text summaries, game links and clear external-source labels.',[['6','specific videos'],['6','game topics'],['YouTube','external host']])}<section class="shell video-feature"><div class="video-player"><iframe src="https://www.youtube-nocookie.com/embed/${featured.id}" title="${esc(featured.title)}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><div>${badge('Featured tutorial','lime')}<h2>${esc(featured.title)}</h2><p>${esc(featured.summary)}</p><a href="${href(`/games/${g.slug}/`)}">Open ${esc(g.name)} hub →</a></div></section><section class="video-band video-page"><div class="shell">${sectionHead('VIDEO LIBRARY','Specific videos, not search pages')}<div class="video-grid">${videos.map(videoCard).join('')}</div></div></section><section class="shell creator-note"><div><span class="kicker">CREATOR POLICY</span><h2>Respect the original creator</h2><p>PlayScout embeds or links to the original video, names the source, adds its own concise summary and never republishes a creator’s video file.</p></div><a class="button" href="${href('/about/sources/')}">Read source rules</a></section>`;
  const jsonLd=[{'@context':'https://schema.org','@type':'VideoObject',name:featured.title,description:featured.summary,thumbnailUrl:`https://i.ytimg.com/vi/${featured.id}/hqdefault.jpg`,uploadDate:'2025-01-01',embedUrl:`https://www.youtube-nocookie.com/embed/${featured.id}`}];
  return layout({title:'Mobile game video guides',description:'Watch specific mobile game tutorials and player videos with summaries and links to complete game hubs.',route:'/videos/',active:'Videos',body,jsonLd});
}

function codesPage(){
  const body=`${pageHero('REWARDS TRACKER','Mobile game redeem codes','Copy a code, see its verification state and jump to the matching game hub for redemption context.',[[String(codes.length),'sample entries'],['1 click','copy action'],['Manual','verification gate']])}<section class="shell codes-layout"><div><div class="notice"><strong>Preview data</strong><p>These codes demonstrate the interface and must be verified in game or against an official publisher source before public promotion.</p></div><div class="code-directory">${codes.map(c=>{const g=game(c.game);return `<article><div>${icon(g)}<span><h2>${esc(g.name)}</h2><a href="${href(`/games/${g.slug}/`)}">Game hub →</a></span></div><p>${esc(c.reward)}</p><div class="copy-block"><code>${esc(c.code)}</code><button type="button" data-copy="${esc(c.code)}">Copy code</button></div><small>${esc(c.status)}</small></article>`}).join('')}</div></div><aside><section class="fact-card"><span class="kicker">HOW TO USE</span><h2>Verify before spending time</h2><ol><li>Open the linked game hub.</li><li>Confirm platform and region.</li><li>Check the verification label.</li><li>Copy the exact code.</li><li>Use the official in-game redemption flow.</li></ol></section>${sourceBox()}</aside></section>`;
  return layout({title:'Mobile game redeem codes',description:'Browse mobile game redeem codes with one-click copy actions, verification labels and linked game hubs.',route:'/codes/',active:'Codes',body});
}

function searchPage(){
  const index=[...games.map(x=>({type:'Game',title:x.name,text:`${x.genre} ${x.summary}`,url:href(`/games/${x.slug}/`)})),...guides.map(x=>({type:'Guide',title:x.title,text:x.dek,url:href(`/guides/${x.slug}/`)})),...news.map(x=>({type:'News',title:x.title,text:x.dek,url:href(`/news/${x.slug}/`)}))];
  const body=`${pageHero('SITE SEARCH','Find a game or answer','Search game hubs, guides and news. Results are filtered instantly and remain linked to crawlable pages.')}<section class="shell search-page"><form role="search" action="${href('/search/')}" method="get"><label for="q">Search PlayScout</label><div><input id="q" name="q" type="search" placeholder="Try “Whiteout upgrades”" autocomplete="off" data-site-search><button type="submit">Search</button></div></form><p class="result-count" aria-live="polite" data-search-count>Start typing to search ${index.length} pages.</p><div class="search-results" data-search-results></div><noscript><p>JavaScript is required for preview search. Use the navigation above or the <a href="${href('/sitemap.xml')}">XML sitemap</a>.</p></noscript><script type="application/json" id="search-index">${JSON.stringify(index)}</script></section>`;
  return layout({title:'Search PlayScout',description:'Search PlayScout game hubs, mobile game guides and news.',route:'/search/',body,noindex:true});
}

function aboutPage(type){
  const isSources=type==='sources'; const title=isSources?'Sources and ranking methodology':'Editorial and player contribution policy';
  const body=`${pageHero('ABOUT PLAYSCOUT',title,isSources?'How rankings, changing facts, screenshots and external videos should be collected and verified.':'How editors turn official updates and player experience into useful, accountable game help.')}<div class="shell prose-layout"><article class="prose">${isSources?`<h2>Source hierarchy</h2><p>Production facts should prefer official store APIs, publisher sites and first-party patch notes. Licensed chart providers may supply ranking snapshots. Reputable creator videos and player communities add experience, but they do not override first-party facts.</p><h2>Ranking fields</h2><p>Store rank, chart movement, editorial heat and recommendation status remain separate. Every changing value needs a region, platform, observed time and source record. The public page shows the last successful update and a stale state when a feed fails.</p><h2>Images and video</h2><p>Use publisher-approved press assets, store artwork through permitted APIs, owned screenshots, or licensed images. Keep YouTube videos on the original host using a specific video ID and link back to the creator.</p><h2>Collection workflow</h2><ol><li>Fetch only permitted fields at a respectful rate.</li><li>Store source URL, external ID and observation time.</li><li>Normalize game identity without erasing the source record.</li><li>Send meaningful changes to editorial review.</li><li>Publish only pages that meet the index-quality threshold.</li></ol>`:`<h2>Answer the player’s decision</h2><p>Every guide starts with the task a player wants to complete. The quick answer appears before background, and each step explains its resource cost, version assumptions and likely failure point.</p><h2>Labels carry meaning</h2><p><b>Official source</b> describes first-party material. <b>Editor verified</b> means an editor checked the claim. <b>Player tested</b> records hands-on experience. These labels cannot be added by an automated rewrite alone.</p><h2>Corrections and updates</h2><p>Material changes update the visible modified date and revision note. Expired codes and outdated strategies remain out of current lists. News pages link into durable game hubs so useful context survives after the headline ages.</p><h2>Community contributions</h2><p>Player tips need a game version, clear reproduction steps and permission to publish. Editors rewrite for clarity, preserve attribution and separate observation from confirmed game rules.</p>`}</article><aside>${sourceBox()}<section class="side-list"><span class="kicker">EXPLORE</span><h2>See the system</h2><a href="${href('/rankings/')}">Ranking tables</a><a href="${href('/guides/')}">Guide templates</a><a href="${href('/videos/')}">External video handling</a><a href="${href('/codes/')}">Code verification states</a></section></aside></div>`;
  return layout({title,description:isSources?'PlayScout source hierarchy, chart methodology, media rights and content collection workflow.':'PlayScout editorial standards, verification labels, corrections and player contribution policy.',route:`/about/${type}/`,body});
}

function notFound(){
  const body=`<section class="not-found shell"><span class="error-code">404</span><span class="kicker">PAGE NOT FOUND</span><h1>That route is off the map</h1><p>Search for a game, return to the latest guides, or explore a working path below.</p><form action="${href('/search/')}" method="get"><input name="q" aria-label="Search PlayScout" placeholder="Search games and guides"><button>Search</button></form><div class="collection-grid"><a href="${href('/games/')}"><b>01</b><strong>Browse games</strong><span>12 complete game hubs</span></a><a href="${href('/rankings/')}"><b>02</b><strong>See rankings</strong><span>Free, paid and grossing views</span></a><a href="${href('/guides/')}"><b>03</b><strong>Read guides</strong><span>Step-by-step answers</span></a></div></section>`;
  return layout({title:'Page not found',description:'The requested PlayScout page could not be found.',route:'/404.html',body,noindex:true});
}

async function write(route, html){const file=routeFile(route);await mkdir(path.dirname(file),{recursive:true});await writeFile(file,html);}

await rm(out,{recursive:true,force:true});
await mkdir(out,{recursive:true});
await cp(path.join(root,'public'),out,{recursive:true});
await cp(path.join(root,'src','styles.css'),path.join(out,'styles.css'));
await cp(path.join(root,'src','app.js'),path.join(out,'app.js'));

const pages=[
  ['/',homePage()],['/games/',gamesPage()],['/rankings/',rankingsPage()],['/new-games/',releasesPage()],['/guides/',channelPage('guides')],['/news/',channelPage('news')],['/videos/',videosPage()],['/codes/',codesPage()],['/search/',searchPage()],['/about/sources/',aboutPage('sources')],['/about/editorial-policy/',aboutPage('editorial-policy')]
];
for(const g of games) pages.push([`/games/${g.slug}/`,gamePage(g)]);
for(const item of guides) pages.push([`/guides/${item.slug}/`,articlePage(item,'guides')]);
for(const item of news) pages.push([`/news/${item.slug}/`,articlePage(item,'news')]);
for(const [route,html] of pages) await write(route,html);
await writeFile(path.join(out,'404.html'),notFound());

const indexed=pages.map(([route])=>route).filter(route=>route!='/search/');
const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${indexed.map(route=>`  <url><loc>${absolute(route)}</loc><lastmod>${buildDate}</lastmod></url>`).join('\n')}\n</urlset>\n`;
await writeFile(path.join(out,'sitemap.xml'),sitemap);
await writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${absolute('/sitemap.xml')}\n`);
await writeFile(path.join(out,'.nojekyll'),'');
await writeFile(path.join(out,'feed.xml'),`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${site.name}</title><link>${absolute('/')}</link><description>${site.description}</description>${news.map(n=>`<item><title>${esc(n.title)}</title><link>${absolute(`/news/${n.slug}/`)}</link><description>${esc(n.dek)}</description></item>`).join('')}</channel></rss>`);
console.log(`Built ${pages.length + 1} HTML pages in ${out}`);
